services:
  db:
    image: postgres:18beta2-alpine3.22
    ports:
      - "8050:5432"
    networks:
      - backend

  frontend:
    image: web-chat-front:latest
    ports:
      - "8051:80"
    # develop:
    #   watch:
    #     - path: ./frontend/
    #       action: rebuild
    depends_on:
      - backend

  backend:
    image: web-chat-back:latest
    ports:
      - "8052:8000"
    # develop:
    #   watch:
    #     - path: ./backend/
    #       action: rebuild
    networks:
      - frontend
      - backend
    depends_on:
      - db

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
