# TODO: add volumes
services:
  db:
    image: postgres:18beta2-alpine3.22
    ports:
      - "8082:5432"
    networks:
      - backend

  frontend:
    image: web-chat-frontend:latest
    ports:
      - "8081:80"
    # develop:
    #   watch:
    #     - path: ./frontend/
    #       action: rebuild
    depends_on:
      - backend

  backend:
    image: web-chat-backend:latest
    ports:
      - "8080:8000"
    # develop:
    #   watch:
    #     - path: ./backend/
    #       action: rebuild
    networks:
      - frontend
      - backend
    depends_on:
      - db

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
